//
//  Icons.swift
//  Subscriptions
//
//  Created by Timo Zacherl on 09.01.22.
//
//  Copyright © 2022 Timo Zacherl. All rights reserved.
//
//  This program is licensed under the GPL-3.0 License.
//  A copy of that license should be attached to the bundle.
//  If not, see <https://www.gnu.org/licenses/>
//

import Foundation

// TODO: This needs some work
struct Icon: Identifiable {
    init(_ symbolName: String, label: String) {
        self.symbolName = symbolName
        self.label = label
    }
    
    var id = UUID()
    var symbolName: String
    var label: String
    
    static var list: [Icon] = [Icon("pencil.circle.fill", label: "Pencil"),
                               Icon("pencil.and.outline", label: "Pencil"),
                               Icon("scribble.variable", label: "Scribble"),
                               Icon("highlighter", label: "Highlighter"),
                               Icon("lasso", label: "Lasso"),
                               Icon("lasso.and.sparkles", label: "Lasso"),
                               Icon("trash.circle.fill", label: "Trash can"),
                               Icon("folder.circle.fill", label: "Folder"),
                               Icon("folder.badge.person.crop", label: "Folder with user avatar"),
                               Icon("paperplane", label: "Paper plane"),
                               Icon("paperplane.circle.fill", label: "Paper plane"),
                               Icon("tray", label: "Tray"),
                               Icon("tray.2", label: "Two trays"),
                               Icon("tray.full", label: "Three trays"),
                               Icon("externaldrive", label: "External drive"),
                               Icon("externaldrive.badge.person.crop", label: "External drive with user avatar"),
                               Icon("externaldrive.badge.icloud", label: "External iCloud drive"),
                               Icon("externaldrive.badge.wifi", label: "Wireless external drive"),
                               Icon("externaldrive.badge.timemachine", label: "External Time Machine backup drive"),
                               Icon("internaldrive", label: "Internal drive"),
                               Icon("opticaldiscdrive", label: "Optical disc drive"),
                               Icon("externaldrive.connected.to.line.below", label: "Plugged in external drive"),
                               Icon("archivebox", label: "Archive box"),
                               Icon("doc", label: "Document"),
                               Icon("doc.text", label: "Document with text"),
                               Icon("doc.on.doc", label: "Document on another document"),
                               Icon("doc.on.clipboard", label: "Document on clipboard"),
                               Icon("doc.richtext", label: "Document with text and image"),
                               Icon("doc.plaintext", label: "Document with plain text"),
                               Icon("doc.append", label: "Document with quote"),
                               Icon("doc.text.below.ecg", label: "Medical document"),
                               Icon("doc.text.magnifyingglass", label: "Zoomed in document"),
                               Icon("chart.bar.doc.horizontal", label: "Document with chart"),
                               Icon("square.text.square", label: "Report"),
                               Icon("doc.text.image", label: "Document with text and image"),
                               Icon("list.bullet.rectangle.portrait", label: "Unordered list"),
                               Icon("list.bullet.rectangle", label: "Unordered list"),
                               Icon("list.dash.header.rectangle", label: "Unordered list with image"),
                               Icon("terminal", label: "Terminal"),
                               Icon("note", label: "Note"),
                               Icon("note.text", label: "Note with text"),
                               Icon("calendar", label: "Calendar"),
                               Icon("calendar.circle.fill", label: "Calendar"),
                               Icon("calendar.day.timeline.leading", label: "Calendar timeline"),
                               Icon("book", label: "Book"),
                               Icon("book.circle.fill", label: "Book"),
                               Icon("books.vertical", label: "Books"),
                               Icon("books.vertical.circle.fill", label: "Books"),
                               Icon("book.closed", label: "Closed book"),
                               Icon("book.closed.circle.fill", label: "Closed book"),
                               Icon("character.book.closed", label: "Labeled book"),
                               Icon("text.book.closed", label: "Closed book with text"),
                               Icon("menucard", label: "Menu card"),
                               Icon("greetingcard", label: "Greeting card"),
                               Icon("magazine", label: "Magazine"),
                               Icon("newspaper", label: "Newspaper"),
                               Icon("newspaper.circle.fill", label: "Newspaper"),
                               Icon("heart.text.square", label: "Medical report"),
                               Icon("bookmark", label: "Bookmark"),
                               Icon("bookmark.circle.fill", label: "Bookmark"),
                               Icon("bookmark.square.fill", label: "Bookmark"),
                               Icon("rosette", label: "Rosette"),
                               Icon("graduationcap", label: "Graduation cap"),
                               Icon("graduationcap.circle.fill", label: "Graduation cap"),
                               Icon("ticket", label: "Ticket"),
                               Icon("paperclip", label: "Paper clip"),
                               Icon("paperclip.circle.fill", label: "Paper clip"),
                               Icon("link", label: "Link"),
                               Icon("link.circle.fill", label: "Link"),
                               Icon("personalhotspot", label: "Personal hotspot"),
                               Icon("personalhotspot.circle.fill", label: "Personal hotspot"),
                               Icon("person", label: "Person"),
                               Icon("person.circle.fill", label: "Person"),
                               Icon("person.badge.clock", label: "Clock with user avatar"),
                               Icon("rectangle.inset.filled.and.person.filled", label: "Person in front of a board"),
                               Icon("person.2", label: "Two persons"),
                               Icon("person.2.circle.fill", label: "Two persons"),
                               Icon("person.wave.2", label: "Two persons"),
                               Icon("person.2.wave.2", label: "Two persons"),
                               Icon("person.3", label: "Three persons"),
                               Icon("person.3.sequence", label: "Three persons"),
                               Icon("lanyardcard", label: "Lanyard card"),
                               Icon("person.crop.circle", label: "Avatar"),
                               Icon("person.crop.circle.badge.moon", label: "Sleeping avatar"),
                               Icon("person.crop.square", label: "Avatar"),
                               Icon("person.crop.artframe", label: "Artwork"),
                               Icon("photo.artframe", label: "Framed picture"),
                               Icon("person.crop.rectangle.stack", label: "Cards with avatar"),
                               Icon("person.2.crop.square.stack", label: "Cards with two avatars"),
                               Icon("person.crop.rectangle", label: "Card with avatar"),
                               Icon("person.crop.square.filled.and.at.rectangle", label: "Contact card"),
                               Icon("person.text.rectangle", label: "Contact card"),
                               Icon("command", label: "Command key"),
                               Icon("command.circle.fill", label: "Command key"),
                               Icon("command.square.fill", label: "Command key"),
                               Icon("escape", label: "Escape key"),
                               Icon("power", label: "Power key"),
                               Icon("power.circle.fill", label: "Power key"),
                               Icon("peacesign", label: "Peace sign"),
                               Icon("dot.arrowtriangles.up.right.down.left.circle", label: "Controller keys"),
                               Icon("globe", label: "Globe"),
                               Icon("network", label: "Network"),
                               Icon("network.badge.shield.half.filled", label: "Protected network"),
                               Icon("globe.americas", label: "Globe on American side"),
                               Icon("globe.europe.africa", label: "Globe on European and African side"),
                               Icon("globe.asia.australia", label: "Globe on Australian side"),
                               Icon("sun.min", label: "Sun"),
                               Icon("sun.max", label: "Sun"),
                               Icon("sun.and.horizon", label: "Sun on the horizon"),
                               Icon("sun.dust", label: "Sun behind dust"),
                               Icon("sun.haze", label: "Sun behind haze"),
                               Icon("moon", label: "Moon"),
                               Icon("moon.circle.fill", label: "Moon"),
                               Icon("zzz", label: "Sleeping"),
                               Icon("moon.zzz", label: "Sleeping moon"),
                               Icon("sparkle", label: "Sparkle"),
                               Icon("sparkles", label: "Sparkles"),
                               Icon("moon.stars", label: "Moon with stars"),
                               Icon("cloud", label: "Cloud"),
                               Icon("cloud.drizzle", label: "Drizzle"),
                               Icon("cloud.rain", label: "Rain"),
                               Icon("cloud.heavyrain", label: "Heavy rain"),
                               Icon("cloud.fog", label: "Fog"),
                               Icon("cloud.hail", label: "Hail"),
                               Icon("cloud.snow", label: "Snow"),
                               Icon("cloud.sleet", label: "Sleet"),
                               Icon("cloud.bolt", label: "Bolt"),
                               Icon("cloud.bolt.rain", label: "Storm"),
                               Icon("cloud.sun", label: "Cloudy"),
                               Icon("cloud.sun.rain", label: "Rain"),
                               Icon("cloud.sun.bolt", label: "Storm"),
                               Icon("cloud.moon", label: "Moon"),
                               Icon("cloud.moon.rain", label: "Raining"),
                               Icon("cloud.moon.bolt", label: "Bolt"),
                               Icon("smoke", label: "Smoke"),
                               Icon("wind", label: "Wind"),
                               Icon("wind.snow", label: "Snow"),
                               Icon("snowflake", label: "Snowflake"),
                               Icon("snowflake.circle.fill", label: "Snowflake"),
                               Icon("tornado", label: "Tornado"),
                               Icon("tropicalstorm", label: "Tropical storm"),
                               Icon("hurricane", label: "Hurricane"),
                               Icon("thermometer.sun", label: "Warm thermometer"),
                               Icon("thermometer.snowflake", label: "Cold thermometer"),
                               Icon("thermometer", label: "Thermometer"),
                               Icon("aqi.low", label: "Low air quality index"),
                               Icon("aqi.medium", label: "Medium air quality index"),
                               Icon("aqi.high", label: "High air quality index"),
                               Icon("humidity", label: "humidity"),
                               Icon("umbrella", label: "Umbrella"),
                               Icon("flame", label: "Flame"),
                               Icon("flame.circle.fill", label: "Flame"),
                               Icon("light.min", label: "Minimum light"),
                               Icon("light.max", label: "Maximum light"),
                               Icon("rays", label: "Rays"),
                               Icon("slowmo", label: "Slow motion"),
                               Icon("timelapse", label: "Timelapse"),
                               Icon("keyboard", label: "Keyboard"),
                               Icon("rectangle.3.group", label: "Three rectangles"),
                               Icon("square.grid.3x2", label: "Grid"),
                               Icon("square.grid.2x2", label: "Grid"),
                               Icon("circle.hexagongrid", label: "Grid"),
                               Icon("circle.hexagongrid.circle.fill", label: "Grid"),
                               Icon("circle.grid.cross", label: "Grid"),
                               Icon("seal", label: "Seal"),
                               Icon("checkmark.seal", label: "Seal with checkmark"),
                               Icon("exclamationmark.triangle", label: "Warning sign"),
                               Icon("drop", label: "Drop"),
                               Icon("drop.circle.fill", label: "Drop"),
                               Icon("play", label: "Play"),
                               Icon("play.circle.fill", label: "Play"),
                               Icon("play.rectangle.fill", label: "Play"),
                               Icon("pause", label: "Pause"),
                               Icon("pause.circle.fill", label: "Pause"),
                               Icon("pause.rectangle.fill", label: "Pause"),
                               Icon("stop", label: "Stop"),
                               Icon("stop.circle.fill", label: "Stop"),
                               Icon("record.circle", label: "Record"),
                               Icon("playpause", label: "Play and pause"),
                               Icon("backward", label: "Go backward"),
                               Icon("forward", label: "Go forward"),
                               Icon("backward.end", label: "Go to the end"),
                               Icon("forward.end", label: "Go to the start"),
                               Icon("backward.frame", label: "Move one frame backward"),
                               Icon("forward.frame", label: "Move on frame forward"),
                               Icon("eject", label: "Eject volume"),
                               Icon("eject.circle.fill", label: "Eject volume"),
                               Icon("mount", label: "Mount volume"),
                               Icon("memories", label: "Memories"),
                               Icon("shuffle", label: "Shuffle"),
                               Icon("shuffle.circle.fill", label: "Shuffle"),
                               Icon("repeat", label: "Repeat"),
                               Icon("repeat.circle.fill", label: "Repeat"),
                               Icon("infinity", label: "Infinity"),
                               Icon("infinity.circle.fill", label: "Infinity"),
                               Icon("megaphone", label: "Megaphone"),
                               Icon("speaker", label: "Speaker"),
                               Icon("speaker.circle.fill", label: "Speaker"),
                               Icon("speaker.zzz", label: "Speaker"),
                               Icon("speaker.wave.1", label: "Speaker"),
                               Icon("speaker.wave.2", label: "Speaker"),
                               Icon("speaker.wave.2.circle.fill", label: "Speaker"),
                               Icon("speaker.wave.3", label: "Speaker"),
                               Icon("music.note", label: "Music note"),
                               Icon("music.note.list", label: "List of music notes"),
                               Icon("music.quarternote.3", label: "Three music notes"),
                               Icon("music.mic", label: "Microphone"),
                               Icon("music.mic.circle.fill", label: "Microphone"),
                               Icon("swift", label: "Swift"),
                               Icon("magnifyingglass", label: "Magnifying glass"),
                               Icon("magnifyingglass.circle.fill", label: "Magnifying glass"),
                               Icon("sparkle.magnifyingglass", label: "Magnifying glass"),
                               Icon("location.magnifyingglass", label: "Magnifying glass"),
                               Icon("loupe", label: "Loupe"),
                               Icon("mic", label: "Microphone"),
                               Icon("mic.circle.fill", label: "Microphone"),
                               Icon("mic.square.fill", label: "Microphone"),
                               Icon("circle", label: "Circle"),
                               Icon("circle.lefthalf.filled", label: "Circle with left half filled"),
                               Icon("circle.tophalf.filled", label: "Circle with top half filled"),
                               Icon("circle.inset.filled", label: "Filled circle"),
                               Icon("circle.dashed.inset.filled", label: "Filled circle with dashed outline"),
                               Icon("circle.dotted", label: "Dotted circle"),
                               Icon("circlebadge.2", label: "Two circles"),
                               Icon("smallcircle.circle", label: "Circle with dot in the middle"),
                               Icon("target", label: "Target"),
                               Icon("capsule", label: "Capsule"),
                               Icon("capsule.lefthalf.filled", label: "Capsule with left half filled"),
                               Icon("capsule.tophalf.filled", label: "Capsule with top half filled"),
                               Icon("capsule.portrait", label: "Standing capsule"),
                               Icon("capsule.portrait.lefthalf.filled", label: "Standing capsule with left half filled"),
                               Icon("capsule.portrait.tophalf.filled", label: "Standing capsule with top half filled"),
                               Icon("capsule.portrait.inset.filled", label: "Filled standing capsule"),
                               Icon("placeholdertext.fill", label: "Placeholder for text"),
                               Icon("square", label: "Square"),
                               Icon("square.dashed", label: "Dashed square"),
                               Icon("hand.raised.square.on.square.fill", label: "Raised hand on squares"),
                               Icon("sparkles.square.filled.on.square", label: "Sparkles on squares"),
                               Icon("app", label: "App"),
                               Icon("play.rectangle.on.rectangle.fill", label: "Play button on rectangle"),
                               Icon("play.rectangle.on.rectangle.circle.fill", label: "Play button on rectangle"),
                               Icon("triangle", label: "Triangle"),
                               Icon("triangle.inset.filled", label: "Filled triangle"),
                               Icon("diamond", label: "Diamond"),
                               Icon("diamond.circle.fill", label: "Diamond on circle"),
                               Icon("diamond.inset.filled", label: "Filled diamond"),
                               Icon("octagon", label: "Octagon"),
                               Icon("hexagon", label: "Hexagon"),
                               Icon("pentagon", label: "Pentagon"),
                               Icon("suit.heart", label: "Suit heart"),
                               Icon("suit.club", label: "Suit club"),
                               Icon("suit.spade", label: "Suit spade"),
                               Icon("suit.diamond", label: "Suit diamond"),
                               Icon("heart", label: "Heart"),
                               Icon("heart.circle.fill", label: "Heart on circle"),
                               Icon("heart.square.fill", label: "Heart on square"),
                               Icon("heart.rectangle.fill", label: "Heart on rectangle"),
                               Icon("bolt.heart.fill", label: "Bolt in heart"),
                               Icon("rhombus", label: "Rhombus"),
                               Icon("star", label: "Start"),
                               Icon("star.circle.fill", label: "Star on circle"),
                               Icon("star.square.fill", label: "Star on square"),
                               Icon("flag", label: "Flag"),
                               Icon("flag.circle.fill", label: "Flag on circle"),
                               Icon("flag.square.fill", label: "Flag on square"),
                               Icon("flag.2.crossed", label: "Two crossed flags"),
                               Icon("flag.filled.and.flag.crossed", label: "Two different crossed flag"),
                               Icon("location", label: "Location"),
                               Icon("location.circle.fill", label: "Location on circle"),
                               Icon("location.square.fill", label: "Location on square"),
                               Icon("airtag.radiowaves.forward", label: "Active AirTag"),
                               Icon("airtag", label: "AirTag"),
                               Icon("bell", label: "Bell"),
                               Icon("bell.circle.fill", label: "Bell on circle"),
                               Icon("bell.square.fill", label: "Bell on square"),
                               Icon("bell.and.waveform", label: "Bell with waves"),
                               Icon("bell.badge", label: "Bell with badge"),
                               Icon("bell.badge.circle.fill", label: "Bell with badge on circle"),
                               Icon("tag", label: "Tag"),
                               Icon("tag.circle.fill", label: "Tag on circle"),
                               Icon("tag.square.fill", label: "Tag on square"),
                               Icon("bolt", label: "Bolt"),
                               Icon("bolt.circle.fill", label: "Bolt on circle"),
                               Icon("bolt.square.fill", label: "Bolt on square"),
                               Icon("bolt.shield.fill", label: "Bolt on shield"),
                               Icon("bolt.badge.a", label: "Bolt (Ampere)"),
                               Icon("bolt.horizontal.circle", label: "Horizontal bolt"),
                               Icon("eye", label: "Eye"),
                               Icon("eye.circle.fill", label: "Eye on circle"),
                               Icon("eye.square.fill", label: "Eye on square"),
                               Icon("tshirt", label: "T-Shirt"),
                               Icon("eyes", label: "Eyes"),
                               Icon("eyebrow", label: "Eyebrow"),
                               Icon("nose", label: "Nose"),
                               Icon("mustache", label: "Mustache"),
                               Icon("mouth", label: "Mouth"),
                               Icon("eyeglasses", label: "Glasses"),
                               Icon("facemask", label: "Face mask"),
                               Icon("brain.head.profile", label: "Brain in head"),
                               Icon("brain", label: "Brain"),
                               Icon("icloud", label: "iCloud"),
                               Icon("icloud.circle.fill", label: "iCloud on Circle"),
                               Icon("icloud.square.fill", label: "iCloud on Square"),
                               Icon("lock.icloud", label: "Locked iCloud"),
                               Icon("key.icloud", label: "iCloud credentials"),
                               Icon("flashlight.off.fill", label: "Flashlight (off)"),
                               Icon("flashlight.on.fill", label: "Flashlight (on)"),
                               Icon("camera", label: "Camera"),
                               Icon("camera.circle.fill", label: "Camera on circle"),
                               Icon("camera.on.rectangle", label: "Camera on rectangle"),
                               Icon("message", label: "Message"),
                               Icon("message.circle.fill", label: "Message on circle"),
                               Icon("bubble.right", label: "Chat bubble"),
                               Icon("bubble.right.circle.fill", label: "Chat bubble on circle"),
                               Icon("quote.opening", label: "Opening quote"),
                               Icon("quote.closing", label: "Closing quote"),
                               Icon("quote.bubble", label: "Chat bubble with quote"),
                               Icon("star.bubble", label: "Chat bubble with star"),
                               Icon("character.bubble", label: "Chat bubble with character"),
                               Icon("text.bubble", label: "Chat bubble with text"),
                               Icon("captions.bubble", label: "Chat bubble with captions"),
                               Icon("rectangle.3.group.bubble.left", label: "Chat bubble with three rectangles"),
                               Icon("ellipsis.bubble", label: "Chat bubble with ellipsis"),
                               Icon("phone.bubble.left.fill", label: "Chat bubble with phone"),
                               Icon("video.bubble.left.fill", label: "Chat bubble with video (FaceTime)"),
                               Icon("bubble.left.and.bubble.right", label: "Communicating chat bubbles"),
                               Icon("phone", label: "Phone"),
                               Icon("phone.circle.fill", label: "Phone on circle"),
                               Icon("video", label: "Video (FaceTime)"),
                               Icon("video.circle.fill", label: "Video on circle (FaceTime)"),
                               Icon("video.square.fill", label: "Video on square (FaceTime)"),
                               Icon("envelope", label: "Envelope"),
                               Icon("envelope.circle.fill", label: "Envelope on circle"),
                               Icon("envelope.open", label: "Open envelope"),
                               Icon("envelope.badge", label: "Envelope with badge"),
                               Icon("envelope.badge.shield.half.filled", label: "Protected envelope"),
                               Icon("mail.stack", label: "Mails"),
                               Icon("mail", label: "Mail"),
                               Icon("mail.and.text.magnifyingglass", label: "Zoomed in mail"),
                               Icon("gear", label: "Gear"),
                               Icon("gear.circle.fill", label: "Gear on circle"),
                               Icon("gearshape", label: "Gear rim shape"),
                               Icon("gearshape.circle.fill", label: "Gear rim shape on circle"),
                               Icon("gearshape.2", label: "Two gear rim shapes"),
                               Icon("signature", label: "Signature"),
                               Icon("line.3.crossed.swirl.circle", label: "Photo snap"),
                               Icon("scissors", label: "Scissors"),
                               Icon("ellipsis.circle", label: "Ellipsis on circle"),
                               Icon("ellipsis.rectangle", label: "Ellipsis on rectangle"),
                               Icon("bag", label: "Bag"),
                               Icon("bag.circle.fill", label: "Bag on circle"),
                               Icon("cart", label: "Cart"),
                               Icon("cart.circle.fill", label: "Cart on circle"),
                               Icon("creditcard", label: "Credit card"),
                               Icon("creditcard.circle.fill", label: "Credit card on circle"),
                               Icon("giftcard", label: "Gift card"),
                               Icon("wallet.pass", label: "Wallet pass"),
                               Icon("wand.and.rays", label: "Wand"),
                               Icon("crop", label: "Crop"),
                               Icon("dial.min", label: "Dial"),
                               Icon("dial.max", label: "Dial"),
                               Icon("gyroscope", label: "Gyroscope"),
                               Icon("gauge", label: "Gauge"),
                               Icon("speedometer", label: "Speedometer"),
                               Icon("barometer", label: "Barometer"),
                               Icon("metronome", label: "Metronome"),
                               Icon("amplifier", label: "Amplifier"),
                               Icon("dice", label: "Dice"),
                               Icon("pianokeys", label: "Piano keys"),
                               Icon("tuningfork", label: "Tuning fork"),
                               Icon("paintbrush", label: "Paint brush"),
                               Icon("paintbrush.pointed", label: "Pointed paint brush"),
                               Icon("bandage", label: "Bandage"),
                               Icon("ruler", label: "Ruler"),
                               Icon("level", label: "Level"),
                               Icon("lines.measurement.horizontal", label: "Measurement"),
                               Icon("wrench", label: "Wrench"),
                               Icon("hammer", label: "Hammer"),
                               Icon("screwdriver", label: "Screwdriver"),
                               Icon("eyedropper", label: "Eye dropper"),
                               Icon("wrench.and.screwdriver", label: "Wrench and screwdriver"),
                               Icon("applescript", label: "AppleScript"),
                               Icon("scroll", label: "Scroll"),
                               Icon("stethoscope", label: "Stethoscope"),
                               Icon("printer", label: "Printer"),
                               Icon("scanner", label: "Scanner"),
                               Icon("faxmachine", label: "Fax machine"),
                               Icon("briefcase", label: "Briefcase"),
                               Icon("case", label: "Case"),
                               Icon("latch.2.case", label: "Case with two latches"),
                               Icon("cross.case", label: "First aid case"),
                               Icon("suitcase", label: "Suitcase"),
                               Icon("suitcase.cart", label: "Suitcase on cart"),
                               Icon("theatermasks", label: "Theater masks"),
                               Icon("puzzlepiece.extension", label: "Puzzle piece"),
                               Icon("puzzlepiece", label: "Puzzle piece"),
                               Icon("homekit", label: "Homekit"),
                               Icon("house", label: "House"),
                               Icon("music.note.house", label: "Music note in house"),
                               Icon("building.columns", label: "Ancient Greek building"),
                               Icon("signpost.left", label: "Signpost"),
                               Icon("building", label: "Building"),
                               Icon("building.2", label: "Two buildings"),
                               Icon("lock", label: "Lock"),
                               Icon("lock.circle.fill", label: "Lock on circle"),
                               Icon("lock.square.fill", label: "Lock on square"),
                               Icon("lock.square.stack.fill", label: "Lock on squares"),
                               Icon("lock.rectangle.fill", label: "Lock on rectangle"),
                               Icon("lock.rectangle.stack.fill", label: "Lock on rectangles"),
                               Icon("lock.rectangle.on.rectangle.fill", label: "Lock on rectangles side by side"),
                               Icon("lock.shield.fill", label: "Lock on shield"),
                               Icon("lock.open", label: "Open lock"),
                               Icon("key", label: "Key"),
                               Icon("wifi", label: "Wifi"),
                               Icon("wifi.circle.fill", label: "Wifi on circle"),
                               Icon("wifi.square.fill", label: "Wifi on square"),
                               Icon("pin", label: "Pin"),
                               Icon("pin.circle.fill", label: "Pin on circle"),
                               Icon("pin.square.fill", label: "Pin on square"),
                               Icon("mappin", label: "Map pin"),
                               Icon("mappin.circle.fill", label: "Map pin on circle"),
                               Icon("mappin.square.fill", label: "Map pin on square"),
                               Icon("mappin.and.ellipse", label: "Map pin and ellipse"),
                               Icon("map", label: "Map"),
                               Icon("map.circle.fill", label: "Map on circle"),
                               Icon("safari", label: "Safari"),
                               Icon("move.3d", label: "Move (3D)"),
                               Icon("scale.3d", label: "Scale (3D)"),
                               Icon("rotate.3d", label: "Rotate (3D)"),
                               Icon("torus", label: "Torus"),
                               Icon("rotate.left", label: "Rotate left"),
                               Icon("selection.pin.in.out", label: "Select pin in and out"),
                               Icon("powerplug", label: "Power plug"),
                               Icon("timeline.selection", label: "Selection on timeline"),
                               Icon("cpu", label: "CPU"),
                               Icon("memorychip", label: "Memory chip (RAM)"),
                               Icon("opticaldisc", label: "Optical disc"),
                               Icon("display", label: "Display"),
                               Icon("display.2", label: "Displays"),
                               Icon("desktopcomputer", label: "Desktop computer"),
                               Icon("pc", label: "PC"),
                               Icon("macpro.gen1", label: "Mac Pro 1. Generation"),
                               Icon("macpro.gen2", label: "Mac Pro 2. Generation"),
                               Icon("macpro.gen3", label: "Mac Pro 3. Generation"),
                               Icon("macpro.gen3.server", label: "Mac Pro 3. Generation in Rack"),
                               Icon("server.rack", label: "Server rack"),
                               Icon("xserve", label: "Xserve"),
                               Icon("laptopcomputer", label: "Laptop computer"),
                               Icon("laptopcomputer.and.iphone", label: "Laptop computer and iPhone"),
                               Icon("ipad.and.iphone", label: "iPad and iPhone"),
                               Icon("macmini", label: "Mac Mini"),
                               Icon("airport.express", label: "Airport Express"),
                               Icon("airport.extreme", label: "Airport Extreme"),
                               Icon("airport.extreme.tower", label: "Airport Extreme Tower"),
                               Icon("ipod", label: "iPod"),
                               Icon("ipodshuffle.gen1", label: "iPod Shuffle 1. Generation"),
                               Icon("ipodshuffle.gen2", label: "iPod Shuffle 2. Generation"),
                               Icon("ipodshuffle.gen3", label: "iPod Shuffle 3. Generation"),
                               Icon("ipodshuffle.gen4", label: "iPod Shuffle 4. Generation"),
                               Icon("ipodtouch", label: "iPod Touch"),
                               Icon("ipodtouch.landscape", label: "iPod Touch in landscape mode"),
                               Icon("flipphone", label: "Flip phone"),
                               Icon("candybarphone", label: "Candy bar phone"),
                               Icon("iphone.homebutton", label: "iPhone with home button"),
                               Icon("iphone.homebutton.landscape", label: "iPhone with home button in landscape mode"),
                               Icon("iphone.homebutton.radiowaves.left.and.right", label: "iPhone with home button with radio waves"),
                               Icon("iphone", label: "iPhone"),
                               Icon("iphone.landscape", label: "iPhone in landscape mode"),
                               Icon("iphone.radiowaves.left.and.right", label: "iPhone with radio waves"),
                               Icon("apps.iphone", label: "iPhone with apps"),
                               Icon("iphone.smartbatterycase.gen2", label: "Smart battery case for iPhones 2. Generation"),
                               Icon("iphone.smartbatterycase.gen1", label: "Smart battery case for iPhones 1. Generation"),
                               Icon("ipad.homebutton", label: "iPad with home button"),
                               Icon("ipad.homebutton.landscape", label: "iPad with home button in landscape mode"),
                               Icon("ipad", label: "iPad"),
                               Icon("ipad.landscape", label: "iPad in landscape mode"),
                               Icon("apps.ipad", label: "iPad with apps"),
                               Icon("applepencil", label: "Apple Pencil"),
                               Icon("magicmouse", label: "Magic Mouse"),
                               Icon("computermouse", label: "Computer mouse"),
                               Icon("applewatch", label: "Apple Watch"),
                               Icon("applewatch.watchface", label: "Apple Watch with watch face"),
                               Icon("applewatch.side.right", label: "Right side of Apple Watch"),
                               Icon("watchface.applewatch.case", label: "Apple Watch with watch face and without watch band"),
                               Icon("airpodsmax", label: "AirPods Max"),
                               Icon("beats.headphones", label: "Beats headphones"),
                               Icon("headphones", label: "Headphones"),
                               Icon("earbuds", label: "Earbuds"),
                               Icon("earbuds.case", label: "Earbuds case"),
                               Icon("earpods", label: "EarPods"),
                               Icon("airpods", label: "AirPods"),
                               Icon("airpods.chargingcase", label: "Charging case for AirPods"),
                               Icon("airpods.chargingcase.wireless", label: "Wireless charging case for AirPods"),
                               Icon("airpodspro", label: "AirPods Pro"),
                               Icon("airpodspro.chargingcase.wireless", label: "Charging case for AirPods Pro"),
                               Icon("airpods.gen3", label: "AirPods 3. Generation"),
                               Icon("airpods.gen3.chargingcase.wireless", label: "Charging case for 3. Generation AirPods"),
                               Icon("beats.earphones", label: "Beats Earphones"),
                               Icon("beats.powerbeatspro", label: "Beats Powerbeats Pro"),
                               Icon("beats.powerbeats", label: "Beats Powerbeats"),
                               Icon("beats.powerbeats3", label: "Beats Powerbeats 3"),
                               Icon("beats.studiobuds", label: "Beats Studio Buds"),
                               Icon("beats.studiobuds.chargingcase", label: "Charging case for Beats Studio Buds"),
                               Icon("beats.fit.pro", label: "Beats Fit Pro"),
                               Icon("beats.fit.pro.chargingcase", label: "Charging case for Beats Fit Pro"),
                               Icon("beats.powerbeatspro.chargingcase", label: "Charging case for Beats Powerbeats Pro"),
                               Icon("homepodmini", label: "HomePod Mini"),
                               Icon("homepodmini.2", label: "Two HomePod Minis"),
                               Icon("homepod.and.homepodmini", label: "HomePod and HomePod Mini"),
                               Icon("hifispeaker.and.homepodmini", label: "Hifi Speaker and HomePod Mini"),
                               Icon("homepod", label: "HomePod"),
                               Icon("homepod.2", label: "Two HomePods"),
                               Icon("hifispeaker.and.homepod", label: "Hifi Speaker and HomePod"),
                               Icon("hifispeaker", label: "Hifi Speaker"),
                               Icon("hifispeaker.2", label: "Two Hifi Speakers"),
                               Icon("appletv", label: "Apple TV"),
                               Icon("homepod.and.appletv", label: "HomePod and Apple TV"),
                               Icon("homepodmini.and.appletv", label: "HomePod Mini and Apple TV"),
                               Icon("hifispeaker.and.appletv", label: "Hifi Speaker and Apple TV"),
                               Icon("appletvremote.gen1", label: "Apple TV Remote 1. Generation"),
                               Icon("appletvremote.gen2", label: "Apple TV Remote 2. Generation"),
                               Icon("appletvremote.gen3", label: "Apple TV Remote 3. Generation"),
                               Icon("appletvremote.gen4", label: "Apple TV Remote 4. Generation"),
                               Icon("magsafe.batterypack", label: "Magsafe Battery Pack"),
                               Icon("mediastick", label: "Media Stick (USB Stick)"),
                               Icon("cable.connector", label: "Cable connector"),
                               Icon("cable.connector.horizontal", label: "Horizontal cable connector"),
                               Icon("radio", label: "Radio"),
                               Icon("tv", label: "TV"),
                               Icon("sparkles.tv", label: "Sparkles on TV"),
                               Icon("4k.tv", label: "4K TV"),
                               Icon("music.note.tv", label: "Music note on TV"),
                               Icon("play.tv", label: "Play button on tV"),
                               Icon("photo.tv", label: "Picture on TV"),
                               Icon("tv.and.hifispeaker.fill", label: "TV and Hifi Speaker"),
                               Icon("tv.and.mediabox", label: "TV and Mediabox"),
                               Icon("airplayvideo", label: "AirPlay Video"),
                               Icon("airplayaudio", label: "AirPlay Audio"),
                               Icon("dot.radiowaves.left.and.right", label: "Radio waves in two directions"),
                               Icon("dot.radiowaves.forward", label: "Radio waves on one side"),
                               Icon("wave.3.forward", label: "Three forward facing waves"),
                               Icon("wave.3.forward.circle.fill", label: "Three forward facing waves on circle"),
                               Icon("dot.radiowaves.up.forward", label: "RSS Feed"),
                               Icon("antenna.radiowaves.left.and.right", label: "Antenna with radio waves"),
                               Icon("antenna.radiowaves.left.and.right.circle.fill", label: "Antenna with radio waves in two directions"),
                               Icon("pip", label: "Picture in picture"),
                               Icon("guitars", label: "Guitars"),
                               Icon("airplane", label: "Airplane"),
                               Icon("airplane.circle.fill", label: "Airplane on circle"),
                               Icon("airplane.arrival", label: "Arrival of airplane"),
                               Icon("airplane.departure", label: "Departure of airplane"),
                               Icon("car", label: "Car"),
                               Icon("car.circle.fill", label: "Car on circle"),
                               Icon("bolt.car", label: "Bolt in car (electric car)"),
                               Icon("bolt.car.circle.fill", label: "Bolt in car on circle (electric car on circle)"),
                               Icon("car.2", label: "Two cars"),
                               Icon("bus", label: "Bus"),
                               Icon("bus.doubledecker", label: "Double decker bus"),
                               Icon("tram", label: "Tram"),
                               Icon("tram.fill.tunnel", label: "Tram in tunnel"),
                               Icon("cablecar", label: "Cablecar"),
                               Icon("ferry", label: "Ferry"),
                               Icon("car.ferry", label: "Car ferry"),
                               Icon("train.side.front.car", label: "Front car of train"),
                               Icon("train.side.middle.car", label: "Middle car of train"),
                               Icon("train.side.rear.car", label: "Rear car of train"),
                               Icon("bicycle", label: "Bicycle"),
                               Icon("bicycle.circle.fill", label: "Bicycle on circle"),
                               Icon("scooter", label: "Scooter"),
                               Icon("parkingsign", label: "Parking sign"),
                               Icon("parkingsign.circle.fill", label: "Parking sign on circle"),
                               Icon("fuelpump", label: "Fuelpump"),
                               Icon("fuelpump.circle.fill", label: "Fuelpump on circle"),
                               Icon("fanblades", label: "Fan blades"),
                               Icon("bed.double", label: "Double bed"),
                               Icon("bed.double.circle.fill", label: "Double bed on circle"),
                               Icon("lungs", label: "Lungs"),
                               Icon("allergens", label: "Allergens"),
                               Icon("pills", label: "Pills"),
                               Icon("pills.circle.fill", label: "Pills on circle"),
                               Icon("testtube.2", label: "Two testtubes"),
                               Icon("ivfluid.bag", label: "IV fluid bag"),
                               Icon("cross.vial", label: "Vial with cross"),
                               Icon("cross", label: "Cross"),
                               Icon("cross.circle.fill", label: "Cross on circle"),
                               Icon("hare", label: "Hare"),
                               Icon("tortoise", label: "Tortoise"),
                               Icon("pawprint", label: "Paw print"),
                               Icon("pawprint.circle.fill", label: "Paw print on circle"),
                               Icon("ant", label: "Ant"),
                               Icon("ant.circle.fill", label: "Ant on circle"),
                               Icon("ladybug", label: "Ladybug"),
                               Icon("leaf", label: "Leaf"),
                               Icon("leaf.circle.fill", label: "Leaf on circle"),
                               Icon("film", label: "Film"),
                               Icon("film.circle.fill", label: "Film on circle"),
                               Icon("sportscourt", label: "Sports court"),
                               Icon("face.smiling", label: "Smiling face"),
                               Icon("face.smiling.fill", label: "Filled smiling face"),
                               Icon("face.dashed.fill", label: "Filled face with dashed outline"),
                               Icon("crown", label: "Crown"),
                               Icon("comb", label: "Comb"),
                               Icon("qrcode", label: "QR Code"),
                               Icon("barcode", label: "Barcode"),
                               Icon("viewfinder", label: "Viewfinder"),
                               Icon("viewfinder.circle.fill", label: "Viewfinder on circle"),
                               Icon("barcode.viewfinder", label: "Barcode viewfinder"),
                               Icon("qrcode.viewfinder", label: "QR Code viewfinder"),
                               Icon("camera.viewfinder", label: "Camera viewfinder"),
                               Icon("faceid", label: "FaceID"),
                               Icon("doc.viewfinder", label: "Document viewfinder"),
                               Icon("location.viewfinder", label: "Location viewfinder"),
                               Icon("person.fill.viewfinder", label: "Person viewfinder"),
                               Icon("text.viewfinder", label: "Text viewfinder"),
                               Icon("dot.viewfinder", label: "Dot viewfinder"),
                               Icon("dot.circle.viewfinder", label: "Outlined dot viewfinder"),
                               Icon("photo", label: "Photo"),
                               Icon("photo.circle.fill", label: "Photo on circle"),
                               Icon("text.below.photo", label: "Text below photo"),
                               Icon("checkerboard.rectangle", label: "Checkerboard"),
                               Icon("camera.metering.center.weighted", label: "Camera metering center weighted"),
                               Icon("camera.metering.matrix", label: "Camera metering matrix"),
                               Icon("camera.aperture", label: "Camera aperture"),
                               Icon("photo.on.rectangle", label: "Photo on rectangle"),
                               Icon("photo.on.rectangle.angled", label: "Angled photo on rectangle"),
                               Icon("sparkles.rectangle.stack", label: "Sparkles on rectangles"),
                               Icon("sidebar.leading", label: "Leading sidebar"),
                               Icon("macwindow", label: "Mac window"),
                               Icon("text.and.command.macwindow", label: "Text and command in Mac window"),
                               Icon("keyboard.macwindow", label: "Keyboard in Mac window"),
                               Icon("mosaic", label: "Mosaic"),
                               Icon("square.on.square.squareshape.controlhandles", label: "Squares inside control handles"),
                               Icon("squareshape.controlhandles.on.squareshape.controlhandles", label: "Two control handles"),
                               Icon("pano", label: "Pano"),
                               Icon("flowchart", label: "Flowchart"),
                               Icon("rectangle.connected.to.line.below", label: "Rectangle connected to line below"),
                               Icon("shield", label: "Shield"),
                               Icon("shield.lefthalf.filled", label: "Shield with filled left half"),
                               Icon("checkerboard.shield", label: "Checkerboard shield"),
                               Icon("switch.2", label: "Two switches"),
                               Icon("point.topleft.down.curvedto.point.bottomright.up", label: "Point from top left down to bottom right"),
                               Icon("app.connected.to.app.below.fill", label: "Filled square connected to another one below"),
                               Icon("slider.horizontal.3", label: "Three horizontal sliders"),
                               Icon("slider.horizontal.below.rectangle", label: "Horizontal slider below rectangle"),
                               Icon("slider.vertical.3", label: "Three vertical sliders"),
                               Icon("cube", label: "Cube"),
                               Icon("cube.transparent", label: "Transparent cube"),
                               Icon("shippingbox", label: "Shipping box"),
                               Icon("arkit", label: "ARKit"),
                               Icon("cone", label: "Cone"),
                               Icon("pyramid", label: "Pyramid"),
                               Icon("livephoto", label: "Live photo button"),
                               Icon("livephoto.play", label: "Play button inside live photo button"),
                               Icon("scope", label: "Scope"),
                               Icon("helm", label: "Helm"),
                               Icon("clock", label: "Clock"),
                               Icon("deskclock", label: "Desk clock"),
                               Icon("alarm", label: "Alarm"),
                               Icon("stopwatch", label: "Stopwatch"),
                               Icon("timer", label: "Timer"),
                               Icon("gamecontroller", label: "Game controller"),
                               Icon("l.joystick", label: "Left joystick on controller"),
                               Icon("r.joystick", label: "Right joystick on controller"),
                               Icon("dpad", label: "DPad on controller"),
                               Icon("circle.circle.fill", label: "Circle button on controller"),
                               Icon("square.circle.fill", label: "Square button on controller"),
                               Icon("triangle.circle.fill", label: "Triangle button on controller"),
                               Icon("l.rectangle.roundedbottom.fill", label: "Left button on controller"),
                               Icon("l1.rectangle.roundedbottom.fill", label: "L1 button on controller"),
                               Icon("l2.rectangle.roundedtop.fill", label: "L2 button on controller"),
                               Icon("r.rectangle.roundedbottom.fill", label: "Right button on controller"),
                               Icon("r1.rectangle.roundedbottom.fill", label: "R1 button on controller"),
                               Icon("r2.rectangle.roundedtop.fill", label: "R2 button on controller"),
                               Icon("lb.rectangle.roundedbottom.fill", label: "LB button on controller"),
                               Icon("rb.rectangle.roundedbottom.fill", label: "RB button on controller"),
                               Icon("lt.rectangle.roundedtop.fill", label: "LT button on controller"),
                               Icon("rt.rectangle.roundedtop.fill", label: "RT button on controller"),
                               Icon("zl.rectangle.roundedtop.fill", label: "ZL button on controller"),
                               Icon("zr.rectangle.roundedtop.fill", label: "ZR button on controller"),
                               Icon("logo.playstation", label: "Playstation Logo"),
                               Icon("logo.xbox", label: "Xbox Logo"),
                               Icon("paintpalette", label: "Color palette"),
                               Icon("cup.and.saucer", label: "Cup and saucer"),
                               Icon("takeoutbag.and.cup.and.straw", label: "Takeout bag, cup and straw"),
                               Icon("fork.knife", label: "Fork and knife"),
                               Icon("figure.walk", label: "Walking figure"),
                               Icon("figure.stand", label: "Standing figure"),
                               Icon("figure.stand.line.dotted.figure.stand", label: "Dotted line between two standing figures"),
                               Icon("figure.wave", label: "Waving figure"),
                               Icon("figure.roll", label: "Rolling figure in wheelchair"),
                               Icon("ear", label: "Ear"),
                               Icon("ear.and.waveform", label: "Ear with waves"),
                               Icon("hand.raised", label: "Raised hand"),
                               Icon("hand.thumbsup", label: "Thumbs up"),
                               Icon("hand.thumbsdown", label: "Thumbs down"),
                               Icon("hand.point.up.left", label: "Hand points towards the upper left"),
                               Icon("hand.draw", label: "Drawing hand"),
                               Icon("hand.tap", label: "Tapping hand"),
                               Icon("rectangle.and.hand.point.up.left", label: "Hand pointing on a rectangle"),
                               Icon("hand.point.left", label: "Hand points towards the left side"),
                               Icon("hand.point.right", label: "Hand points towards the right side"),
                               Icon("hand.point.up", label: "Hand points towards the upper side"),
                               Icon("hand.point.up.braille", label: "Hands points on braille"),
                               Icon("hand.point.down", label: "Hand points towards the bottom"),
                               Icon("hand.wave", label: "Waving hands"),
                               Icon("hands.clap", label: "Clapping hands"),
                               Icon("hands.sparkles", label: "Clapping hands with sparkles"),
                               Icon("cylinder", label: "Cylinder"),
                               Icon("cylinder.split.1x2", label: "Splited cylinder"),
                               Icon("chart.bar", label: "Bar chart"),
                               Icon("chart.pie", label: "Pie chart"),
                               Icon("chart.bar.xaxis", label: "Bar chart on x-axis"),
                               Icon("chart.line.uptrend.xyaxis", label: "Line chart with upwards trend"),
                               Icon("burst", label: "Burst"),
                               Icon("waveform.path.ecg", label: "ECG waveform path"),
                               Icon("waveform.path", label: "Waveform path"),
                               Icon("point.3.connected.trianglepath.dotted", label: "Three points connected by dotted line in triangle path"),
                               Icon("waveform", label: "Waveform"),
                               Icon("waveform.and.magnifyingglass", label: "Waveform and magnifying glass"),
                               Icon("waveform.and.mic", label: "Waveform and microphone"),
                               Icon("simcard", label: "Sim card"),
                               Icon("simcard.2", label: "Two sim cards"),
                               Icon("sdcard", label: "SD Card"),
                               Icon("esim", label: "eSim"),
                               Icon("touchid", label: "TouchID"),
                               Icon("bonjour", label: "Bonjour"),
                               Icon("atom", label: "Atom"),
                               Icon("scalemass", label: "Scale mass"),
                               Icon("gift", label: "Gift"),
                               Icon("app.badge", label: "Badge on app icon"),
                               Icon("appclip", label: "AppClip"),
                               Icon("app.gift", label: "App gift"),
                               Icon("studentdesk", label: "Student desk"),
                               Icon("hourglass", label: "Hourglass"),
                               Icon("banknote", label: "Banknote"),
                               Icon("paragraphsign", label: "Paragraph sign"),
                               Icon("purchased", label: "Purchased"),
                               Icon("perspective", label: "Perspective"),
                               Icon("aspectratio", label: "Aspect ratio"),
                               Icon("camera.filters", label: "Camera filters"),
                               Icon("skew", label: "Skew"),
                               Icon("grid", label: "Grid"),
                               Icon("burn", label: "Burn"),
                               Icon("lifepreserver", label: "Life preserver"),
                               Icon("recordingtape", label: "Recording tape"),
                               Icon("binoculars", label: "Binoculars"),
                               Icon("battery.100", label: "Battery on 100%"),
                               Icon("battery.75", label: "Battery on 75%"),
                               Icon("battery.50", label: "Battery on 50%"),
                               Icon("battery.25", label: "Battery on 25%"),
                               Icon("battery.0", label: "Battery on 0%"),
                               Icon("battery.100.bolt", label: "Loading battery"),
                               Icon("minus.plus.batteryblock", label: "Negative and positive battery block"),
                               Icon("bolt.batteryblock", label: "Loading battery block"),
                               Icon("lightbulb", label: "Lightbulb"),
                               Icon("fibrechannel", label: "Fibre channel"),
                               Icon("checklist", label: "Checklist"),
                               Icon("list.dash", label: "Dashed list"),
                               Icon("list.bullet", label: "Bullet list"),
                               Icon("list.number", label: "Ordered list"),
                               Icon("text.quote", label: "Text quote"),
                               Icon("list.and.film", label: "List and film"),
                               Icon("textformat.size", label: "Textformat: Size"),
                               Icon("textformat", label: "Textformat"),
                               Icon("textformat.alt", label: "Textformat: Alt"),
                               Icon("textformat.superscript", label: "Textformat: Superscript"),
                               Icon("textformat.subscript", label: "Textformat: Subscript"),
                               Icon("textformat.abc.dottedunderline", label: "Textformat: Dotted underline"),
                               Icon("bold", label: "Bold"),
                               Icon("italic", label: "Italic"),
                               Icon("underline", label: "Underline"),
                               Icon("strikethrough", label: "Strikethrough"),
                               Icon("shadow", label: "Shadow"),
                               Icon("view.2d", label: "View in 2D"),
                               Icon("view.3d", label: "View in 3D"),
                               Icon("character.cursor.ibeam", label: "Character cursor"),
                               Icon("fx", label: "FX"),
                               Icon("f.cursive", label: "Cursive F"),
                               Icon("k", label: "K"),
                               Icon("sum", label: "Sum"),
                               Icon("percent", label: "Percent"),
                               Icon("function", label: "Function"),
                               Icon("fn", label: "Fn"),
                               Icon("textformat.123", label: "Textformat: 123"),
                               Icon("a.magnify", label: "Zoomed in A"),
                               Icon("info", label: "Info"),
                               Icon("info.circle.fill", label: "Info on circle"),
                               Icon("at", label: "@ (at)"),
                               Icon("at.circle.fill", label: "@ (at) on circle"),
                               Icon("questionmark", label: "? (question mark)"),
                               Icon("questionmark.circle.fill", label: "? (question mark) on circle"),
                               Icon("exclamationmark", label: "! (exclamation mark)"),
                               Icon("exclamationmark.circle.fill", label: "! (exclamation mark) on circle"),
                               Icon("exclamationmark.shield.fill", label: "! (exclamation mark) on shield"),
                               Icon("plus", label: "+ (plus)"),
                               Icon("minus", label: "- (minus)"),
                               Icon("plusminus", label: "+- (plus minus)"),
                               Icon("plus.forwardslash.minus", label: "+/- (plus/minus)"),
                               Icon("minus.forwardslash.plus", label: "-/+ (minus/plus)"),
                               Icon("multiply", label: "* (multiply)"),
                               Icon("divide", label: "/ (divide)"),
                               Icon("equal", label: "= (equal)"),
                               Icon("lessthan", label: "< (less than)"),
                               Icon("greaterthan", label: "> (greater than)"),
                               Icon("chevron.left.forwardslash.chevron.right", label: "Coding"),
                               Icon("parentheses", label: "Parentheses"),
                               Icon("curlybraces", label: "Curly braces"),
                               Icon("ellipsis.curlybraces", label: "Ellipsis between curly braces"),
                               Icon("number", label: "Number"),
                               Icon("x.squareroot", label: "Square root"),
                               Icon("xmark", label: "Close"),
                               Icon("xmark.circle.fill", label: "Close"),
                               Icon("checkmark", label: "Checkmark"),
                               Icon("checkmark.circle.fill", label: "Checkmark"),
                               Icon("applelogo", label: "Apple logo")]
}
                                
